//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberUygulamasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haberler
    {
        public int HaberID { get; set; }
        public int KategoriID { get; set; }
        public int YazarID { get; set; }
        public string Baslik { get; set; }
        public string Resim { get; set; }
        public string Icerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
    }
}
