//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityUygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hastalar
    {
        public int ID { get; set; }
        public string TC { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Tel { get; set; }
        public int BolumID { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
    }
}
